apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: exchange-rate-deploy
  labels:
    app: exchange-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-rate
  template:
    metadata:
      labels:
        app: exchange-rate
    spec:
      containers:
      - name: exchange-rate
        image: yuriadams/exchange_rate:latest
        ports:
        - containerPort: 3001
